### ISSUE TITLE
When will your paper be public? Could u upload it to arxiv?

### ISSUE THREAD

**Issue by abcdvzz** [JDAI-CV/DCL#1]

**Comment by zhangyongshun** [comment]
excellent work！Some question here.

**Comment by lemonrr** [comment]
Same question, can't find your paper on arxiv

**Comment by wyvernbai** [comment]
Thanks for your interests. Here is the pre-print version: [http://ylbai.me/DCL_cvpr19.pdf](http://ylbai.me/DCL_cvpr19.pdf)
