### ISSUE TITLE
ct_train/val/test file

### ISSUE THREAD

**Issue by yangyangkiki** [JDAI-CV/DCL#11]
Hi,

Can you share the ct_train/val/test.txt files of  CUB/ Stanford Car/Aircraft to us?

Thank you.

Kind regards.

Kiki

**Comment by Chen94yue** [comment]
I added these files, although I think it will only take you a little time to generate them.

**Comment by yangyangkiki** [comment]
ok, thx a lot.

**Comment by yangyangkiki** [comment]
Hi, I download CUB on this web: 
http://www.vision.caltech.edu/visipedia/CUB-200.html 
But I found some images in the train.txt that provided by you are not exist.  I don't know which part I did is wrong.
Look forward to you reply.
Thanks

**Comment by Chen94yue** [comment]
The right address for CUB-200-2011 dataset is: http://www.vision.caltech.edu/visipedia/CUB-200-2011.html
Your address is the homepage for CUB-200-2010 dataset

**Comment by yangyangkiki** [comment]
ok, thank you.

**Comment by yangyangkiki** [comment]
hi, should  label = self.labels[item] (line 84) in dataset_DCL.py be revised to label = self.labels[item] -1 ?

**Comment by Chen94yue** [comment]
@yangyangkiki You are right. Sorry, I forgot the code was changed.

**Comment by Chen94yue** [comment]
You are right. Sorry, I forget the code has been changed.

**Comment by yangyangkiki** [comment]
ok.

**Comment by yangyangkiki** [comment]
Hi @Chen94yue ，

I am confused that why you do this:  img = img.crop((10, 10, widthcut-10, highcut-10)) https://github.com/JDAI-CV/DCL/blob/master/transforms/functional.py#L377 in transforms/functional.py when you swap the image.

So why you remove the edged 10 pixels from the image? Can you explain this? If I do not do this, I think it is better to find the similar patch through the mean value calculated before.

Thank you.

**Comment by Chen94yue** [comment]
The images with border are common in CUB images. This operation cuts the border of the images and is useless in the latest version.  If your training images don't have border, you can comment out this line.

**Comment by yangyangkiki** [comment]
Got it. Thank you.
