### ISSUE TITLE
'MainModel' object has no attribute 'module'

### ISSUE THREAD

**Issue by OaDsis** [JDAI-CV/DCL#13]
Traceback (most recent call last):                                                                                          │
  File "train.py", line 194, in <module>                                                                                    │
    ignored_params1 = list(map(id, model.module.classifier.parameters()))                                                   │
  File "/home/weiyanyan/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 518, in __getattr__         │
    type(self).__name__, name))                                                                                             │
AttributeError: 'MainModel' object has no attribute 'module'

**Comment by Chen94yue** [comment]
How many GPUs do you have?

**Comment by OaDsis** [comment]
> How many GPUs do you have?

just one GPU for using.

**Comment by OaDsis** [comment]
I change the code  from 'ignored_params = list(map(id, model.**module.**classifier.parameters()))' to 'ignored_params = list(map(id, model.classifier.parameters()))', will this operation fix the AttributeError mentioned above?
I have a 12GB ram GPU for training. After i change the code above, now the AttributeError is gone and print 'CUDA error: out of memory'.

**Comment by Chen94yue** [comment]
Just one GPU is hard to train this model, you can refer to [#12 ](https://github.com/JDAI-CV/DCL/issues/12)

**Comment by OaDsis** [comment]
OK,thanks for your reply.
