### ISSUE TITLE
fix random seed to get identical result

### ISSUE THREAD

**Issue by goldentimecoolk** [JDAI-CV/DCL#17]
Hi, thanks for sharing your work. Can you please fix the random seed so that we could have a consistent result? which may help further research. (I failed to fix it, cause some random sources reach beyond my knowledge.)

Thanks again.

**Comment by akira-l** [comment]
Thanks for the advice. We had considered this issue. Since we'd like to apply DCL in various datasets, settings(loss functions, etc.), even to different tasks, the fixed seed seems not suitable, at least not flexible to individual requirements in various cases. 

Besides, if you want the consistent result, the checkpoint in the elder branch may be useful, or just run enough epoch and experiments to test the particular tasks you. :)

**Comment by goldentimecoolk** [comment]
> Thanks for the advice. We had considered this issue. Since we'd like to apply DCL in various datasets, settings(loss functions, etc.), even to different tasks, the fixed seed seems not suitable, at least not flexible to individual requirements in various cases.
> 
> Besides, if you want the consistent result, the checkpoint in the elder branch may be useful, or just run enough epoch or experiments to test the particular tasks you want with the new branch. :)

Thanks for your reply. I just want to reproduce the result of fine-grained classification on CUB, stanford cars and aircraft datasets. I think they could share the same global random seed. However, as I set it as: 

```
def setup_seed(seed):
     torch.manual_seed(seed)
     torch.cuda.manual_seed_all(seed)
     np.random.seed(seed)
     random.seed(seed)
     torch.backends.cudnn.deterministic = True
```

results are stable, but not exactly the same. Can you help me?
Thank you!

**Comment by akira-l** [comment]
That's weird. In my view, two ways are optional. 

1. try to test with fixed / random seed in your code, and find out the gap. If the gap is not significant, perhaps, there are something wrong in your code or environment.

2. try the checkpoint in the elder branch

**Comment by goldentimecoolk** [comment]
Okay！I will try the solutions. -:)

**Comment by goldentimecoolk** [comment]
Hi, I'm back. I fixed the random seed and could get the same result every time. There were random sources that were ignored before. However, the result didnt go up. It even fall to 86.7%. I will try some other initial seeds.
