### ISSUE TITLE
FileNotFoundError while python train.py as the Readme.md proposed

### ISSUE THREAD

**Issue by Jin398111152** [JDAI-CV/DCL#18]
After orgnaizing the CUB dataset as the Readme.md suggest, while python train.py for training from scatch it reported 'FileNotFoundError: [Errno 2] File b'./dataset/CUB_200_2011/anno/ct_train.txt' does not exist: b'./dataset/CUB_200_2011/anno/ct_train.txt''.How could I fix it?Thanks a lot.

**Comment by akira-l** [comment]
It seems that no corresponding annotation files are placed. Prepare your data according to the instructions in README.

**Comment by Jin398111152** [comment]
Thanks for your reply.I organzied the data as README.But it still reported I missed the 'cr_train.txt'，but I couldn't find it neither the CUB dataset nor the datasets in the your project.

**Comment by Jin398111152** [comment]
> It seems that no corresponding annotation files are placed. Prepare your data according to the instructions in README.

I have solved it,thanks for your help.

**Comment by ahsan856jalal** [comment]
@Jin398111152 Can you please tell me how you solved this as I have the same problem

**Comment by xiabc612** [comment]
rename 'datasets' to 'dataset'
