### ISSUE TITLE
Some inconsistance bettween paper and code

### ISSUE THREAD

**Issue by hiyijian** [JDAI-CV/DCL#2]
Dear @wyvernbai,  
   I might found some  inconsistance bettween paper and code. Hopefuly looking forward to your further explaination.
   Firstly, you mentioned θadv ∈ Rd×2 in the paper, which means discriminator is a two-way classifier. However, the code says it is a 2 * num_class way classifier.
   Sencondly, adv loss is usually optimized by a minmax game, but I did not find any minmax optimazation within your code. Is that Intended？
   Lastly,  the paper says  "the outputs are handled by an ReLU and an average pooling to
get a map with the size of 2×N ×N" to produce location map. But convmask(2048, 1, ,1) + avepool2 in the code might not take that effects?

**Comment by wyvernbai** [comment]
You are right, but it doesn't hurt the final performance. We will update a new version soon.

**Comment by hiyijian** [comment]
@wyvernbai I still didnt found any adv training(minmax game) code in your latest repo. Did I miss anything?

**Comment by wyvernbai** [comment]
@hiyijian The code about adv training is implemented in `classifier_swap` function.

**Comment by tranvnhan** [comment]
> @hiyijian The code about adv training is implemented in `classifier_swap` function.

Where exactly is `classifier_swap` function in your code?
