### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for MainModel

### ISSUE THREAD

**Issue by NanakoSasaki** [JDAI-CV/DCL#21]
Dear Authors:
  I use single GPU(TITAN Xp 12G) to train and test on datasets(STCAR,CUB,AIR). No errors appear while training. But when I test, I get the same problem on three dataset which is the weight could not be loaded. Details is shown as below.
/usr/bin/python3.6 /media/duanzd/local/DCL-master/test.py --ver test --acc_report --data STCAR --backbone resnet50 --save /media/duanzd/local/DCL_weights/net_model/DCL_STCAR/weights_358_508_1.0000_1.0000.pth
Namespace(acc_report=True, backbone='resnet50', batch_size=16, crop_resolution=448, dataset='STCAR', num_workers=16, resize_resolution=512, resume='/media/duanzd/local/DCL_weights/net_model/DCL_STCAR/weights_358_508_1.0000_1.0000.pth', save_suffix=None, swap_num=[7, 7], version='test')
resnet50
Traceback (most recent call last):
  File "/media/duanzd/local/DCL-master/test.py", line 93, in <module>
    model.load_state_dict(model_dict)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for MainModel:
	While copying the parameter named "classifier_swap.weight", whose dimensions in the model are torch.Size([2, 2048]) and whose dimensions in the checkpoint are torch.Size([392, 2048]).
    I wonder if there are some wrong settings when I train the weight. Thank you for help.

**Comment by Chen94yue** [comment]
We have two set for DL('--cls_2' or '--cls_mul'), you can see #19 for detail. The classifier_swap layer are different in these two set and need to be consistent in training and testing.

**Comment by NanakoSasaki** [comment]
Thank you very much! According to your answer， the problem has been solved. :)
