### ISSUE TITLE
nn.DataParallel problem

### ISSUE THREAD

**Issue by NoneLand** [JDAI-CV/DCL#24]
When use the nn.DataParallel, I got OOM even setting train_batch to 1. And after I shutdown nn.DataParallel, it runs smoothly with train batch setting to 16 and use 12G memory of titan xp. And by looking issues in the previous code, i got that train DCL with train batch 16 use 88GB meory of 4 P40s. And I can't figure out why it uses so much memory and did I got things right. 
My environment info is as below:
OS: Ubuntu 16.04
Pytorch: .0.4.1
nvidia-driver: 384.90
CUDA; 9.0

**Comment by akira-l** [comment]
What's the resolution rate and backbone? DCL needs more memory due to the swapped data.

**Comment by NoneLand** [comment]
Thansk for your reply.
The command I use to train model is :
`python train.py --data xx --epoch 360 --backbone resnet50 --tb 16 --tnw 16 --vb 32 --vnw 32 --lr 0.0008 --lr_step 60 --cls_lr_ratio 10 --start_epoch 0 --detail training_descibe --size 512 --crop 448 --cls_mul --swap_num 2 2`
And by shutdown `nn.DataParallel`,I mean

`# model = nn.DataParallel(model)

    # optimizer prepare
    # if Config.use_backbone:
    #     ignored_params = list(map(id, model.module.classifier.parameters()))
    # else:
    #     ignored_params1 = list(map(id, model.module.classifier.parameters()))
    #     ignored_params2 = list(map(id, model.module.classifier_swap.parameters()))
    #     ignored_params3 = list(map(id, model.module.Convmask.parameters()))
    #
    #     ignored_params = ignored_params1 + ignored_params2 + ignored_params3
    if Config.use_backbone:
        ignored_params = list(map(id, model.classifier.parameters()))
    else:
        ignored_params1 = list(map(id, model.classifier.parameters()))
        ignored_params2 = list(map(id, model.classifier_swap.parameters()))
        ignored_params3 = list(map(id, model.Convmask.parameters()))

        ignored_params = ignored_params1 + ignored_params2 + ignored_params3`
