### ISSUE TITLE
performance on FGVC-Aircraft dataset

### ISSUE THREAD

**Issue by goldentimecoolk** [JDAI-CV/DCL#26]
Hello, I retrained DCL on Aircraft dataset. All hyper parameters except N followed default setting. When I set N as 7 and 2, I got the highest accuracy 90.4% and 92.3% respectively. But the reported results were 92.2% and 93.0%.
Is there anything wrong? Could someone provide suggestions on reproducing the reported results?
THX!!!

**Comment by lijain** [comment]
你好，请问你的数据是怎么加入训练的。数据格式好像和voc那种有一些区别

**Comment by lijain** [comment]
I have finished my training. Why does my prediction use test to reload the model. Load? State? Dict (model? Dict) has been out of dimension mismatch
