### ISSUE TITLE
test.py size of tensor doesn't match

### ISSUE THREAD

**Issue by Zambashilidye** [JDAI-CV/DCL#28]
hi,
I successfully run the training code. But when it turned to test. I don't know how to set the parser.
I run train.py --cls_mul with resnet50

in test.py,  I use val set for test,  annotated line63-66( dont use ct_test.txt ), annotated line 73 (undefined) , annotated line 94 (only using 1 device), replace line89 resume to the path of my model.

But it turn out that in line111:
RuntimeError: the size of tensor a( **)  must match the size of tensor b(2) at non-singleton dimension 1

a () is the same as the clsnum I set in config.py, however output[1] seems not to match that size.

I'm really interested with your project and what's wrong with my process..

**Comment by lijain** [comment]
I have the same question

**Comment by Zambashilidye** [comment]
Well...
I solved this problem by adapting config.py
#124  self.cls_2 = True
#125  self.cls_2xmul = False
changed to 
#124  self.cls_2 = False
#125  self.cls_2xmul = True

and test.py seems to work... Though I don't know why lol.

**Comment by lijain** [comment]
Is self.cls Chu 2 classified as 2? Another is multiclassification

**Comment by Zambashilidye** [comment]
> Is self.cls Chu 2 classified as 2? Another is multiclassification

You can check LoadModel.py Line 43-46.

**Comment by lijain** [comment]
Thank you. Let me see.



------------------ 原始邮件 ------------------
发件人: "Cheng Tan"<notifications@github.com>;
发送时间: 2019年10月24日(星期四) 上午10:34
收件人: "JDAI谢谢了，我看看



















          Thank you. Let me see.-CV/DCL"<DCL@noreply.github.com>;
抄送: "利剑"<1632401541@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [JDAI-CV/DCL] test.py size of tensor doesn't match (#28)



 
Is self.cls Chu 2 classified as 2? Another is multiclassification
  
You can check LoadModel.py Line 43-46.
