### ISSUE TITLE
 No module named 'models'

### ISSUE THREAD

**Issue by dongzhi0312** [JDAI-CV/DCL#3]
`Traceback (most recent call last):
  File "train_rel.py", line 16, in <module>
    from models.resnet_swap_2loss_add import resnet_swap_2loss_add
ModuleNotFoundError: No module named 'models'`

from resnet_swap_2loss_add import resnet_swap_2loss_add
AttributeError: 'resnet_swap_2loss_add' object has no attribute 'module'

maybe you just delete .module if you just you use one gpu.
when I use  model = nn.DataParallel(model) my gpu is stuck and kill -9 pid is not response

**Comment by akira-l** [comment]
You should move resnet_swap_2loss_add.py into models and let your programme find the model class.
