### ISSUE TITLE
very hard to understand the code.

### ISSUE THREAD

**Issue by lychenpan** [JDAI-CV/DCL#31]

**Comment by Chen94yue** [comment]
？？？？

**Comment by universebang** [comment]
> ？？？？

Hi！There are some problems in your code about swapping， You can't guarantee that each local area after swapping will differ by 2k units from the original area

**Comment by universebang** [comment]
For example，transforms/functional.py/swap()

**Comment by Chen94yue** [comment]
> For example，transforms/functional.py/swap()

Yes, you are right. I have tried to fix this bug. But this demo version is the most stable for final accuracy.

**Comment by zamliman** [comment]
I had to make several adjustments to make your code work, I also tried training using your technique with default settings on CUB dataset with resnet-50 per instructions with 180 and 360 epochs. Unfortunately I could not reproduce the accuracy you achieved in the paper

**Comment by zamliman** [comment]
It also seems like you introduced cls_mul which differs from the paper, where the adversarial loss is more similar to cls_2 option. Is this correct?

**Comment by Chen94yue** [comment]
> It also seems like you introduced cls_mul which differs from the paper, where the adversarial loss is more similar to cls_2 option. Is this correct?

In our experiments, these two loss have similar performance on CUB dataset. Besides, Cls_mul performs better on big datasets, such as FGVC Challenge 2019. We can confirm that it is possible to get the results in the paper based on this code. Maybe your experimental environment is different from ours.
