### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by gengyanlei** [JDAI-CV/DCL#33]
作者，您好。
我想咨询一下，basline的问题，我用resnet50在CUB上面训练，学习率设置和您的代码一样，共训练300epoch，每90个epoch降低到上一次学习率的1/10，但是我发现在前面训练的过程中，网络测试精度上升非常缓慢，到最后也只是52%的测试精度；
请问您训练baseline有什么技巧么？
谢谢。

**Comment by Chen94yue** [comment]
数据增强怎么做的？

**Comment by gengyanlei** [comment]
按照训练随机裁剪512，测试中心裁剪448；

**Comment by Chen94yue** [comment]
你的训练和测试图像大小至少要保持一样吧，不能一个大一个小，可以参考DCL的图像增强的写法，去掉区域的随机扰动就行了。

**Comment by gengyanlei** [comment]
不不，我是训练先变成512再随机裁剪成448，测试时中心裁剪成448

**Comment by Chen94yue** [comment]
测试先变成512，再中心裁剪448

**Comment by gengyanlei** [comment]
对对，总之都是先变成512，然后训练时随机裁剪，测试时中心裁剪

**Comment by Chen94yue** [comment]
应该按照DCL的增强策略和训练参数设置，只是不带区域扰动，就能训出较高的baseline，你看一下你什么位置不一样。

**Comment by gengyanlei** [comment]
那我试试直接在他的代码上运行baseline试试，我是自己写的代码，数据增强比他的增加了概率为0.2的颜色系列扰动。
谢谢您了

**Comment by gengyanlei** [comment]
就是按照初始学习率为0.0008？ 共360个cpoch，每60个epoch降一次学习率。但是他论文里面写的是180个epoch

**Comment by Chen94yue** [comment]
180个就够了

**Comment by Chen94yue** [comment]
你的最后一个全连接层是不是没有单独设学习率啊？

**Comment by gengyanlei** [comment]
单独设置了学习率了，我再试试哈。用它的代码实验一下。谢谢你啊

**Comment by gengyanlei** [comment]
找到问题所在了，我没有fine-tune成功。哈哈，尴尬

**Comment by lovechenforeverlove** [comment]
> 找到问题所在了，我没有fine-tune成功。哈哈，尴尬

我想问下您这个代码跑通了吗？我在复现代码时出现了一些问题，想要请教一下您
