### ISSUE TITLE
What the mean of swap_law1

### ISSUE THREAD

**Issue by lovebobo** [JDAI-CV/DCL#4]
Hi, I can not understand the use of swap_law1, and why use 24 but not other number
swap_law1 = [(i-24)/49 for i in range(crop_num[0]*crop_num[1])]

**Comment by hiyijian** [comment]
just a "index normalization". 24 is the mean value of 1 to 49

**Comment by lovebobo** [comment]
Thx, and i also notice that some  inconsistance bettween paper and code, like Location Matrix is one channel but in paper two，and the Adversarial Learning Network only use a CrossEntropyLoss

**Comment by akira-l** [comment]
That has been fixed in current version @lovebobo . You can use one or two channels if you want .
