### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by gengyanlei** [JDAI-CV/DCL#41]
作者，你好，你在说明里面写到这个算法已经用到了京东商品识别上面，我想问，CUB的类别仅仅200类，而实际商品类别数量可能上万，并且你的网络有2个全连接，这样全连接导致的显存占用以及参数量会剧增，请问你如何解决这种问题呢。
总是在小规模数据上，并不能很好的看出网络的真实性能的。假如有大规模数据，那么如何能实战呢？

**Comment by Chen94yue** [comment]
京东商城的商品图像搜索是一个复杂的架构，具体实现方案无法给您详细介绍。就分类模型而言，并不会细粒度到商品级，一般是在商城的一级或二级类目进行分类，细粒度的商品采用一些metric learning训练的特征模型进行搜索。

**Comment by gengyanlei** [comment]
好的，非常感谢您的回答。
