### ISSUE TITLE
使用mobilenet作为backbone网络

### ISSUE THREAD

**Issue by bingkunj** [JDAI-CV/DCL#42]
你好，
我是新手上路，resnet50作为特征提取网络，模型太大了，使用mobilenetv2替换resnet50在stanford cars上训练，acc只有0.74。请问大佬是否尝试过轻量型网络，是否适合这类任务，有什么优化措施？

**Comment by Chen94yue** [comment]
模型轻量化了性能自然是会下降的。这在所有任务上都是一样的。

**Comment by bingkunj** [comment]
性能会下降可以理解的，但是下降太多，一般分类任务中mobilenet会比resnet50性能差些，但差的不会太大。我查了一下细粒度分类好像都是vgg或resnet网络，是不是mobilenet不太适合

**Comment by Javacr** [comment]
> 性能会下降可以理解的，但是下降太多，一般分类任务中mobilenet会比resnet50性能差些，但差的不会太大。我查了一下细粒度分类好像都是vgg或resnet网络，是不是mobilenet不太适合

我也想做这方面的实验，mobilenet作为轻量级模型，用在细粒度分类上，性能肯定比不上resnet50，只能在速度上与模型大小上进行比较。而且，还不能直接使用mobilenet作为backbone，可以尝试将resnet中的block用mobilenet中的block替换试试。
