### ISSUE TITLE
why this situation happen?

### ISSUE THREAD

**Issue by redbullet-develop** [JDAI-CV/DCL#43]
![图片](https://user-images.githubusercontent.com/52592491/79679238-c4cf8280-8236-11ea-833d-693e1e76105c.png)

**Comment by redbullet-develop** [comment]
"FileNotFoundError: [Errno 2] File b'./dataset/CUB_200_2011/anno\\train.txt' does not exist: b'./dataset/CUB_200_2011/anno\\tra
in.txt'"

**Comment by dc3ea9f** [comment]
You didn't prepare the dataset well: `train.txt` is not found.
Please refer to [here](https://github.com/JDAI-CV/DCL#datasets-prepare).
