### ISSUE TITLE
保存的模型有一层维度出现偏差

### ISSUE THREAD

**Issue by bolin12** [JDAI-CV/DCL#44]
运行CUB数据集，保存模型，加载后发现有一层维度不一样
saved_model:
......
model.7.2.bn3.running_vartorch.Size([2048])
model.7.2.bn3.num_batches_trackedtorch.Size([])
classifier.weighttorch.Size([200, 2048])
classifier_swap.weighttorch.Size([400, 2048])
Convmask.weighttorch.Size([1, 2048, 1, 1])
Convmask.biastorch.Size([1])

origin_model:
......
model.7.2.bn3.running_vartorch.Size([2048])
model.7.2.bn3.num_batches_trackedtorch.Size([])
classifier.weighttorch.Size([200, 2048])
classifier_swap.weighttorch.Size([2, 2048])
Convmask.weighttorch.Size([1, 2048, 1, 1])
Convmask.biastorch.Size([1])

咋回事呢

**Comment by yunchangxiaoguan** [comment]
> 运行CUB数据集，保存模型，加载后发现有一层维度不一样
> saved_model:
> ......
> model.7.2.bn3.running_vartorch.Size([2048])
> model.7.2.bn3.num_batches_trackedtorch.Size([])
> classifier.weighttorch.Size([200, 2048])
> classifier_swap.weighttorch.Size([400, 2048])
> Convmask.weighttorch.Size([1, 2048, 1, 1])
> Convmask.biastorch.Size([1])
> 
> origin_model:
> ......
> model.7.2.bn3.running_vartorch.Size([2048])
> model.7.2.bn3.num_batches_trackedtorch.Size([])
> classifier.weighttorch.Size([200, 2048])
> classifier_swap.weighttorch.Size([2, 2048])
> Convmask.weighttorch.Size([1, 2048, 1, 1])
> Convmask.biastorch.Size([1])
> 
> 咋回事呢

你好，请问你这个怎么解决的，应该是咱们训练的类变了，但是测试时候读取就出错了
RuntimeError: Error(s) in loading state_dict for MainModel:
	size mismatch for classifier_swap.weight: copying a param with shape torch.Size([2, 2048]) from checkpoint, the shape in current model is torch.Size([6, 2048]).

**Comment by rnlee1998** [comment]
> > 运行CUB数据集，保存模型，加载后发现有一层维度不一样
> > saved_model:
> > ......
> > model.7.2.bn3.running_vartorch.Size([2048])
> > model.7.2.bn3.num_batches_trackedtorch.Size([])
> > classifier.weighttorch.Size([200, 2048])
> > classifier_swap.weighttorch.Size([400, 2048])
> > Convmask.weighttorch.Size([1, 2048, 1, 1])
> > Convmask.biastorch.Size([1])
> > origin_model:
> > ......
> > model.7.2.bn3.running_vartorch.Size([2048])
> > model.7.2.bn3.num_batches_trackedtorch.Size([])
> > classifier.weighttorch.Size([200, 2048])
> > classifier_swap.weighttorch.Size([2, 2048])
> > Convmask.weighttorch.Size([1, 2048, 1, 1])
> > Convmask.biastorch.Size([1])
> > 咋回事呢
> 
> 你好，请问你这个怎么解决的，应该是咱们训练的类变了，但是测试时候读取就出错了
> RuntimeError: Error(s) in loading state_dict for MainModel:
> size mismatch for classifier_swap.weight: copying a param with shape torch.Size([2, 2048]) from checkpoint, the shape in current model is torch.Size([6, 2048]).

请问您是怎么解决的？
