### ISSUE TITLE
给位大佬，能问一下utils里面的Asoftmax和autoaugment与dataset_DCL三个网络主要是做什么的吗？

### ISSUE THREAD

**Issue by sc-huipu-pc** [JDAI-CV/DCL#48]

**Comment by dc3ea9f** [comment]
Asoftmax和autoaugment是我们在FGVC Challenge 2019中尝试的一些方法，dataset_DCL定义了我们DCL方法需要的输入。
如果只关注DCL的话可以忽略前两者。
