### ISSUE TITLE
how can I continue to train from the previous saved model？

### ISSUE THREAD

**Issue by xiabc612** [JDAI-CV/DCL#50]
Follow parameters setting seems doesn't work.  The previous saved model has not been loaded.

python train.py --data product --epoch 60 --backbone senet154 \
                    --tb 96 --tnw 32 --vb 512 --vnw 32 \
                    --lr 0.01 --lr_step 12 \
                    --cls_lr_ratio 10 --start_epoch $LAST_EPOCH \
                    --detail training_descibe4checkpoint --size 512 \
                    --crop 448 --cls_2 --swap_num 7 7

**Comment by miao404** [comment]
hello, I have the same question, have you solved it?
