### ISSUE TITLE
 Large-scale Product Recognition

### ISSUE THREAD

**Issue by bixiaopeng0** [JDAI-CV/DCL#54]
请问 Large-scale Product Recognition 有具体实现代码，论文链接吗？

**Comment by wyvernbai** [comment]
[http://trax-geometry.s3.amazonaws.com/cvpr_challenge/recognition_challenge_technical_reports/1st__Winner+Solution+for+AliProducts+Challenge+Large-scale+Product+Recognition.pdf](http://trax-geometry.s3.amazonaws.com/cvpr_challenge/recognition_challenge_technical_reports/1st__Winner+Solution+for+AliProducts+Challenge+Large-scale+Product+Recognition.pdf)

这个是今年aliproduct比赛的实现方案

**Comment by bixiaopeng0** [comment]
谢谢！
