### ISSUE TITLE
Has anyone retrain the project? I can’t get the accuracy reported in the paper.

### ISSUE THREAD

**Issue by WilyZhao8** [JDAI-CV/DCL#6]
Has anyone retrain the project? Can the accuracy of the paper be achieved? I didn't change the code. And the best result was 0.8669.

**Comment by liuboss1992** [comment]
I retain the project, the result wa 0.8757.

**Comment by wjtan99** [comment]
@liuboss1992 What training parameters did you use? After training 174 epochs with training batch = 16, I got 83%.   How did you divide the training and validation, testing sets on CUB?
